# coding: utf-8

"""
    Algocash API

    This is a Algocash API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: loganph.work@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import algocash_sdk
from algocash_sdk.api.deposit_api import DepositApi  # noqa: E501
from algocash_sdk.rest import ApiException


class TestDepositApi(unittest.TestCase):
    """DepositApi unit test stubs"""

    def setUp(self):
        self.api = DepositApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_deposit(self):
        """Test case for create_deposit

        create a deposit  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
